#! /bin/sh
case "$1" in
	start|"")
		echo -n "Starting miscellaneous setup: "
		MAX_BS=`fw_printenv -n iio_max_block_size || echo 67108864`
		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)

		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
