#!/bin/sh

CONFIGFS=/sys/kernel/config/usb_gadget
GADGET=$CONFIGFS/pluto_comp_gadget
USBD_OPTS="/dev/pluto_ffs/ep0 /usr/sbin/iiod -i -a"

case "$1" in
  start)
 	echo "Starting UDC Gadgets"
	mount configfs -t configfs /sys/kernel/config >> /dev/null

	mkdir $GADGET
	serial=`dmesg | grep  SPI-NOR-UniqueID | cut -d " " -f 4`
	echo $serial > /etc/serial
	sha1=`echo $serial | sha1sum`

	echo 0x0456 > $GADGET/idVendor
	echo 0xb673 > $GADGET/idProduct

	mkdir $GADGET/strings/0x409
	echo "Analog Devices Inc." > $GADGET/strings/0x409/manufacturer
	echo "PlutoSDR (ADALM-PLUTO)" > $GADGET/strings/0x409/product
	echo $serial > $GADGET/strings/0x409/serialnumber

	mkdir $GADGET/functions/ffs.pluto_ffs
	mkdir $GADGET/functions/acm.usb0
	mkdir $GADGET/functions/rndis.0
	mkdir $GADGET/functions/mass_storage.0

#	echo /opt/vfat.img > $GADGET/functions/mass_storage.0/lun.0/file
	echo Y > $GADGET/functions/mass_storage.0/lun.0/removable

	host_addr=`echo -n 00:E0:22; echo $sha1 | dd bs=1 count=6 2>/dev/null | hexdump -v -e '/1 ":%01c""%c"'`
	dev_addr=`echo -n 00; echo $sha1 | dd bs=1 count=10 skip=6 2>/dev/null | hexdump -v -e '/1 ":%01c""%c"'`

	echo $host_addr > $GADGET/functions/rndis.0/host_addr
	echo $dev_addr > $GADGET/functions/rndis.0/dev_addr

	mkdir $GADGET/configs/c.1
	mkdir $GADGET/configs/c.1/strings/0x409
	echo "PlutoSDR (RNDIS/MSD/ACM/IIOUSBD)" > $GADGET/configs/c.1/strings/0x409/configuration
	echo 500 > $GADGET/configs/c.1/MaxPower


	ln -s $GADGET/functions/rndis.0 $GADGET/configs/c.1
	ln -s $GADGET/functions/mass_storage.0 $GADGET/configs/c.1
	ln -s $GADGET/functions/acm.usb0 $GADGET/configs/c.1
	ln -s $GADGET/functions/ffs.pluto_ffs $GADGET/configs/c.1/ffs.pluto_ffs

	mkdir /dev/pluto_ffs
	mount pluto_ffs -t functionfs /dev/pluto_ffs

	start-stop-daemon -S -b -q -m -p /var/run/usbd.pid -x /usr/sbin/usbd -- $USBD_OPTS
	sleep 0.2

	echo ci_hdrc.0 > $GADGET/UDC

	;;
  stop)
	echo -n "Stopping UDC Gadgets ..."
	echo "" > $GADGET/UDC

	start-stop-daemon -K -q -p /var/run/usbd.pid 2>/dev/null

	rm $GADGET/configs/c.1/rndis.0
	rm $GADGET/configs/c.1/mass_storage.0
	rm $GADGET/configs/c.1/acm.usb0
	rm $GADGET/configs/c.1/ffs.pluto_ffs

	rmdir $GADGET/strings/0x409
	rmdir $GADGET/configs/c.1/strings/0x409
	rmdir $GADGET/configs/c.1

	rmdir $GADGET/functions/ffs.pluto_ffs
	#rmdir $GADGET/functions/acm.usb0
	rmdir $GADGET/functions/rndis.0
	rmdir $GADGET/functions/mass_storage.0

	rmdir $GADGET

	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?






