#!/bin/sh

source /etc/device_config

CONFIGFS=/sys/kernel/config/usb_gadget
GADGET=$CONFIGFS/composite_gadget
IIOD_OPTS="-D -F /dev/iio_ffs"

create_iiod_context_attributes() {
	model=$1
	serial=$2

	echo "[Context Attributes]" > /etc/libiio.ini
	echo "hw_model=$model" >> /etc/libiio.ini
	echo -e "hw_serial=$serial\n" >> /etc/libiio.ini
}

case "$1" in
  start)
 	echo "Starting UDC Gadgets"
	mount configfs -t configfs /sys/kernel/config >> /dev/null

	mkdir $GADGET

	model=`cat /sys/firmware/devicetree/base/model | tr / -`

	serial=`dmesg | grep SPI-NOR-UniqueID`
	serial=${serial#*SPI-NOR-UniqueID }

	create_iiod_context_attributes "$model" "$serial"

	echo $serial > /etc/serial
	sha1=`echo $serial | sha1sum`

	echo 0x0456 > $GADGET/idVendor
	echo $USBPID > $GADGET/idProduct

	mkdir $GADGET/strings/0x409
	echo "Analog Devices Inc." > $GADGET/strings/0x409/manufacturer
	echo $PRODUCT > $GADGET/strings/0x409/product
	echo $serial > $GADGET/strings/0x409/serialnumber

	mkdir $GADGET/functions/ffs.iio_ffs
	mkdir $GADGET/functions/acm.usb0
	mkdir $GADGET/functions/rndis.0
	mkdir $GADGET/functions/mass_storage.0

#	echo /opt/vfat.img > $GADGET/functions/mass_storage.0/lun.0/file
	echo Y > $GADGET/functions/mass_storage.0/lun.0/removable

	host_addr=`echo -n 00:E0:22; echo $sha1 | dd bs=1 count=6 2>/dev/null | hexdump -v -e '/1 ":%01c""%c"'`
	dev_addr=`echo -n 00:05:F7; echo $sha1 | dd bs=1 count=6 skip=6 2>/dev/null | hexdump -v -e '/1 ":%01c""%c"'`

	echo $host_addr > $GADGET/functions/rndis.0/host_addr
	echo $dev_addr > $GADGET/functions/rndis.0/dev_addr

	mkdir $GADGET/configs/c.1
	mkdir $GADGET/configs/c.1/strings/0x409
	echo "RNDIS/MSD/ACM/IIOUSBD" > $GADGET/configs/c.1/strings/0x409/configuration
	echo 500 > $GADGET/configs/c.1/MaxPower

	ln -s $GADGET/functions/rndis.0 $GADGET/configs/c.1
	ln -s $GADGET/functions/mass_storage.0 $GADGET/configs/c.1
	ln -s $GADGET/functions/acm.usb0 $GADGET/configs/c.1
	ln -s $GADGET/functions/ffs.iio_ffs $GADGET/configs/c.1/ffs.iio_ffs

	mkdir /dev/iio_ffs
	mount iio_ffs -t functionfs /dev/iio_ffs

	start-stop-daemon -S -b -q -m -p /var/run/iiod.pid -x  /usr/sbin/iiod  -- $IIOD_OPTS
	sleep 0.2

	echo ci_hdrc.0 > $GADGET/UDC

	;;
  stop)
	echo -n "Stopping UDC Gadgets ..."
	echo "" > $GADGET/UDC

	start-stop-daemon -K -q -p /var/run/iiod.pid 2>/dev/null

	rm $GADGET/configs/c.1/rndis.0
	rm $GADGET/configs/c.1/mass_storage.0
	rm $GADGET/configs/c.1/acm.usb0
	rm $GADGET/configs/c.1/ffs.iio_ffs

	rmdir $GADGET/strings/0x409
	rmdir $GADGET/configs/c.1/strings/0x409
	rmdir $GADGET/configs/c.1

	rmdir $GADGET/functions/ffs.iio_ffs
	#rmdir $GADGET/functions/acm.usb0
	rmdir $GADGET/functions/rndis.0
	rmdir $GADGET/functions/mass_storage.0

	rmdir $GADGET

	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?






