#!/bin/sh
# Server-side demuxing by default

source /etc/device_config

case "$1" in
	start)
		echo "Starting dhcpd Daemon& httpd Server"
		start-stop-daemon -S -b -q -m -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
		httpd -h /www
		exit $?
		;;

	stop)
		echo "Stopping dhcpd Server Daemon"
		killall -7 httpd
		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
		exit $?
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
