#!/bin/sh
#
# Keep the main clock in powerdown until used
#

source /etc/device_config

handle_calibration_files() {
	if [[ -s /mnt/jffs2/${CALIBFILENAME} ]]; then
		cp /mnt/jffs2/${CALIBFILENAME} /opt/${CALIBFILENAME}
	elif [[ -s /mnt/jffs2/${CALIBFILENAME_FACTORY} ]]; then
		cp /mnt/jffs2/${CALIBFILENAME_FACTORY} /opt/${CALIBFILENAME}
	fi
}

case "$1" in
 start)
	iio_attr -q -d m2k-fabric clk_powerdown 1
	handle_calibration_files
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
