#!/bin/sh
#
# Start overtemp monitor
#

case "$1" in
  start)
    echo -n "Starting Overtemp Monitor: "

    start-stop-daemon -S -b -q -m -p /var/run/overtemp.pid -x /bin/sh -- /sbin/overtemp_monitor.sh
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;

  stop)
    echo "Stopping overtemp monitor: "
    start-stop-daemon -K -q -p /var/run/overtemp.pid 2>/dev/null
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
