#! /bin/sh

xo_correction() {

	XO_ENV_VAL=`fw_printenv -n xo_correction 2> /dev/null`
	if [ $? -eq 0 ]; then

		for dev in /sys/bus/iio/devices/*; do
			[ `cat ${dev}/name` == "ad9361-phy" ] && DEV_NAME=`basename ${dev}`
		done

		echo ${XO_ENV_VAL} > /sys/bus/iio/devices/${DEV_NAME}/xo_correction
	fi
}


case "$1" in
	start|"")
		echo -n "Starting miscellaneous setup: "
		xo_correction
		echo 1 > /sys/bus/iio/devices/iio:device0/out_altvoltage1_TX_LO_powerdown
		MAX_BS=`fw_printenv -n iio_max_block_size 2> /dev/null || echo 67108864`
		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)

		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
